link:../info_main.adoc[На главную..]

= Mодуль взаимодействия с пользователем

link:../uml_diagrams/user_features.plum[User Features - UML]

== Режимы

Пользователю предоставляется два режима: режим создателя и режим игрока.

*_Возможности режима создателя:_*

-	добавление и удаление слов
-	установка размерности
-	блокировка ячеек

При добавлении слов создатель должен ввести их описание. Составленный список слов будет использован для автоматической генерации кроссворда. По итогу пользователь получит схему кроссворда и список неиспользованных слов. После этого кроссворд можно будет решить или создать новый. 

Ответственный класс: CrossWordConfigurator.

*_Возможности режима игрока:_*

-	проверка правильности решения кроссворда (введенных слов)
-	ввод и удаление слова

_Варианты ввода:_

•	”number – word” – если слово подходит, то оно будет вписано с заменой текущего слова;
•	”number – ” – удаление слова под заданным номером (те заполнение пустым словом)

Ответственный класс: CrossWordPlayer.

== Интерфейс

*_Главное меню:_*

-	Играть
-	Создать кроссворд
-	Помощь
-	Выйти

_Раздел «Играть»:_

Пользователю отображается кроссворд и подсказки. Процесс решения описан в вариантах ввода.

_Раздел «Создать кроссворд»:_

Если кроссворд отсутствует, создателю поочередно потребуется ввести: размер поля, заблокированные ячейки, слова с пояснениями в список для автоматической генерации.
В ином случае, создатель сможет выбрать каждый из этих пунктов для внесения изменений. При изменении размерности – слова, не удовлетворяющие этому условию, из списка автоматически удалятся.


link:crossword_generator.adoc[Генерация]
происходит либо по запросу создателя, либо автоматически при выходе из данного пункта меню.

Разделы «Помощь» и «Выйти» не требуют пояснений.

Ответственный класс взаимодействия: GameMenu.

Ответственный класс отображения: MenuDrawer
